# Generated by Django 4.2.5 on 2023-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
